name: CI

on: [pull_request]

jobs:
  build:
    name: "CI - Pull Request Validations"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Use NodeJs
        uses: actions/setup-node@v3
        id: use-nodejs
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: ./yarn.lock
      - name: yarn install && yarn validate
        working-directory: ./
        run: |
          yarn install --frozen-lockfile
          yarn build
